Set values for datatypes integer, boolean, string in continuous_time_…
OpenModelica/OpenModelica pull request #10916
Opened 2023-07-02 12:05 UTC by nik5346

#10915

2023-07-02 12:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/OpenModelica/OpenModelica?pullRequest=10916) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/OpenModelica/OpenModelica?pullRequest=10916) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/OpenModelica/OpenModelica?pullRequest=10916) it.</sub>

2023-07-05 11:04 UTC, AnHeuermann requested changes
I don't think violating the FMI standard (2.0.4) is the correct solution for the problem you described in #10915.

2023-07-06 08:25 UTC, AnHeuermann commented on OMCompiler/SimulationRuntime/c/fmi/FMI2Common.c
> +    if (FMI2ME->FMISolvingMode == fmi2_instantiated_mode || FMI2ME->FMISolvingMode == fmi2_initialization_mode || FMI2ME->FMISolvingMode == fmi2_event_mode || FMI2ME->FMISolvingMode == fmi2_continuou
> So why not allow it in OpenModelica too? Is there any reason not to do so, besides a formal violation of the standard?

Well, I guess not. But there is a reason FMI and Modelica are standardized in the first place. If everyone would follow a (non existing) perfect standard each model would always work in every tool. Of course this is unrealistic, but following the standard is maybe the best option we have.

@casella Do we have an official approach on this?

Someone could open a change request for FMI 2.0.5 to also allow it.

2023-07-06 08:32 UTC, AnHeuermann commented on OMCompiler/SimulationRuntime/c/fmi/FMI2Common.c
> +    if (FMI2ME->FMISolvingMode == fmi2_instantiated_mode || FMI2ME->FMISolvingMode == fmi2_initialization_mode || FMI2ME->FMISolvingMode == fmi2_event_mode || FMI2ME->FMISolvingMode == fmi2_continuou
The only thing I can see for FMUs linked like

![grafik](https://github.com/OpenModelica/OpenModelica/assets/38031952/fd7a0adc-1ebe-4025-ba9c-98bb55db4885)

to work is to create events for each change of an integer/boolean. Even if they are wrapped with `noEvent`, which is stupid.

Allowing the non-standard function call would be way more easy. But then we need to do it for OMSimulator as well...

2023-07-09 00:09 UTC, closed without merging

2023-07-10 15:23 UTC, casella commented
If it was dropped in 3.0 there was probably a good reason for it. But I would definitely recommend to propose a fix for 2.0.5. Please go ahead with that.

2023-07-13 20:32 UTC, nik5346 commented
@AnHeuermann 
I can't reopen the branch. Here is the branch to merge:
https://github.com/nik5346/OpenModelica/tree/fmi2SetXXX_cont_time