Cmake config
OpenModelica/OpenModelica pull request #6737
Opened 2020-09-07 17:34 UTC by mahge

**_This an updated version of the PR #6648. That was reverted due to issues with compilation of simulationruntimemsvc library.  This fixes that and brings back the changes from the PR._**

This is an attempt to have a CMake configuration support for OMC. Right now the focus is in getting OMCompiler working. 
This is **not ready at all**. It is here just for early discussion. If it is deemed unnecessary it might be removed completely. 

The idea is to aim for recent versions of cmake. (a.k.a "modern" CMake). This means it is intended to work only with **CMake > 3.14**. It should be easy to get this (or later) versions of CMake on most platforms. On _MinGW_ you can use the **Windows** version of CMake which is, right now, at 3.17.2 (stable) 

# How to build
It is pretty straightforward cmake stuff.
It does not give you an _omc executable_ at the moment. But if you want to try it out anyway 

```sh
cd OMCompiler
mkdir build_cmake && cd build_cmake

# Wno-dev to hide some cmake warnings from 3rdParty
cmake .. -Wno-dev -G <your_generator> # e.g. -G "MSYS Makefiles" for OMDev MSYS

make -j -Oline # -Oline for GNU Makefiles so that your colors do not get messed up.
# cmake --build ./ --config Release --parallel 5 # If you want to be generic. 
```

# Benefits
- It forces us to have proper structure. 
- Same build configuration on different platforms.
- _Modern_ CMake: automatic configuration propagation.
  - Cleanly specify for each library:
    - Where is is coming from?
    - Which libraries does it depend on?
    - Where do those libraries come from.
    - What header files does it need?
    - What header files should its dependents use?
    - What compilation flags and options does it need?
    - What compilation flags and options its dependents should use?
    - ...  
- _Potentially_ use different build systems.
  - Ninja
  - MSBuild (one day, in the distant future)
- Clean out of source builds.
- ...

# Potential (Further improvement)
- Use CMake aware package manager, e.g., vcpkg, connan ...
- Use CMake's fetch_content (configure time downloading) to get anything that is not available through package manager or anything that needs patching and custom handling.
 
# Progress

- [x] OMCompiler/3rdParty/(most)
- [x] OMCompiler/Parser
- [x] OMCompiler/Compiler/runtime
- [x] OMCompiler/Compiler/Template
- [x] OMCompiler/SimulationRuntime/c/{OpenModelicaRuntime, OpenModelicaFMIRuntime}
  - More can be added as needed.

- [ ] Figure out a way to cleanly handle the `MetaModelica` source files to build `libOpenModelica`.
  - This is the big one. To simplify things, the idea is to aim for no bootstrapping support yet. Just compilation using installed OMC.
- [ ] Add a header only interface library for all the common include files. e.g. `openmodelica.h`, `revision.h`
- [ ] Handle all libraries in OMCompiler/SimulationRuntime/c. Some are left for later.
- [ ] No free standing "outside" include directories. All includes should come from dependency targets.

- [ ] ... (Many more if this goes on)

2020-09-09 11:47 UTC, AnHeuermann requested changes
Needs some changes to compile on Linux (and/or) Ubuntu 18.04.

But otherwise I'm all for merging this PR.

2020-09-28 09:06 UTC, AnHeuermann approved these changes
I could compile it now.

2020-10-12 17:28 UTC, adrpo commented on OMCompiler/Compiler/.cmake/package_list.txt
> +Absyn
Why do we need this file?

2020-10-12 17:43 UTC, adrpo reviewed
In principle seems fine. Why do we have a file with all the packages listed?
One question: does it work with both cmake and normal compilation at the moment?

I don't like that: if OMC_BOOTSRAPPING then this include, else other include, seems very error prone. I would suggest to move that to an h file that we include everywhere and maybe have those two file have a different name so you can list both of the include directories in the c(makefile) and don't bother with weird relative paths.

2020-10-13 08:31 UTC, mahge commented
>  One question: does it work with both cmake and normal compilation at the moment?

Yes. this will not affect the normal compilation (with *omdev.mingw makefiles) or configuration (with autotools). I tried to explain this when I first started the implementation and then when the issue of [unavailability of recent CMake](https://github.com/OpenModelica/OpenModelica/pull/6648#issuecomment-651014203) came up with the original PR. Jenkins builds (GCC, clang, Linux, Windows), for example, are passing and working as usual in this PR itself and they are using the normal compilation. In fact as it is now it needs to the normal compilation since there is no bootstrapping support (that is, if you clean everything).
 
There is no way I would implement something that will require everyone to have CMake > 3.14 to develop OMC from the get go. That is just not reasonable. I thought that would be obvious. Maybe I should have clarified it a bit more properly.

The only "significant" modifications in this PR are to CMakeLists.txt files that are not used but have been sitting in OpenModelica repository unmodified (except the one in SimRT/c/ as it turned out). The last time the main OMCompiler/CMakeLists.txt file was modified is in 2012. Everything else is either additions or modifications/fixes that should be done in the current build system as well.

2020-10-13 08:39 UTC, mahge commented
> Why do we have a file with all the packages listed?
It should not be there. It was added for ease of development as a quick way to get the list of source files (It should have been name file_name_list or similar as well).

We not have a small C++ code that does the "dependency scanning" for MetaModelica source files. Basically it reads all the imports of every MM file and computes the reverse dependencies for each file. So that we know which files need to be re-translated if a MM source is modified. Ideally the scanner should get the list of MM sources from the same place as the CMake files [here](https://github.com/OpenModelica/OpenModelica/blob/d88d428f581aeb1bbc15c46d2700d6e08e130f89/OMCompiler/Compiler/.cmake/meta_modelica_source_list.cmake). 

It was a bit of work to parse that file and get the filenames. So I decided to put the list in a simple text file for the time being. I thing the best solution might have been to use CMake itself dump that file during configuration from the list of MM files it uses. I will do that.

2020-10-13 08:50 UTC, adrpo commented
Maybe we could have a list of sources that both make and cake can use.

2020-10-13 08:50 UTC, mahge commented
> I don't like that: if OMC_BOOTSRAPPING then this include, else other include, seems very error prone. I would suggest to move that to an h file that we include everywhere and maybe have those two file have a different name so you can list both of the include directories in the c(makefile) and don't bother with weird relative paths.

Yes I do like that at all as well. The current makefiles actually change the _include path_ while keeping the filename the same. Which in my opinion is ever more confusing because you have no idea that a different file with the same name might be included. At least this way you can notice that you are including two different files depending on configuration.

I would have liked to rename the file. However, that would have been a change to bootstrapping that needs to be discussed. 

We can rename the one in OMCompiler/Compiler to `OMCompiler.h` or something similar and keep the other one *BootstrappingHeader. If you have other names you would like let know. Or even better you can rename it and I will rebase this.

2020-10-13 09:14 UTC, mahge commented
> Maybe we could have a list of sources that both make and cake can use.

The current normal compilation does not need the list of files in that format. Instead, it generate Makefile targets and recipes directly using omc. 
This can be done for CMake as well if we use just GNU Makefiles. It would not work for other generators though. To take full advantage of CMake and generate for other build systems, e.g. Visual Studio projects, we need to have an independent dependency scanning system.

2020-10-13 09:18 UTC, mahge commented
> Maybe we could have a list of sources that both make and cake can use.

Sorry I think I got what you meant just now. Unifying it with this [LoadCompilerSources.mo](https://github.com/OpenModelica/OpenModelica/blob/master/OMCompiler/Compiler/boot/LoadCompilerSources.mos).

Ya maybe we can do that. Keep the list of MM sources in one file with full paths and read that with both compilations. That can work.

2020-10-18 21:47 UTC, adrpo approved these changes
OK with me! Let's merge this after the meeting tomorrow.

2020-10-22 06:41 UTC, merged