Fix buffer overflow in Jacobian dump
OpenModelica/OpenModelica pull request #7039
Opened 2020-12-12 15:07 UTC by AnHeuermann

- Increase buffer size
  - Use snprintf to fix security issue and prevent buffer overflow

2020-12-12 15:08 UTC, AnHeuermann commented
Fix for [Trac ticket #6275](https://trac.openmodelica.org/OpenModelica/ticket/6275).

2020-12-14 11:43 UTC, mahge requested changes
It is not easy to read Andreas. I can see that you have an array of double precision floating point numbers that you want to serialize to a string (right?)

Is it giving you the expected results right now? 

Here is what I understood from it:
They all go in to one char array buffer. `snprintf ` null terminates the string that your write to the buffer. So every time you write you get the returned value of "written" characters and use that as a starting point so that you can overwrite the null terminator. 

Is this correct? If so, then this definitely needs some comments or explanation.

2020-12-14 11:45 UTC, mahge commented on OMCompiler/SimulationRuntime/c/simulation/solver/sundials_error.c
> +      throwStreamPrint(NULL, "Buffer overflow!");
It is not easy to read Andreas. I can see that you have an array of double precision floating point numbers that you want to serialize to a string (right?)

Is it giving you the expected results right now?

Here is what I understood from it:
They all go in to one char array buffer. snprintf null terminates the string that your write to the buffer. So every time you write you get the returned value of "written" characters and use that as a starting point so that you can overwrite the null terminator.

Is this correct? If so, then this definitely needs some comments or explanation.

2020-12-14 12:18 UTC, AnHeuermann commented on OMCompiler/SimulationRuntime/c/simulation/solver/sundials_error.c
> +      throwStreamPrint(NULL, "Buffer overflow!");
Ahh, I was not aware that `snprintf` appends a terminating null character at the end. But `sprintf` does the same and that worked. But that would explain the strange results I got in-between. I think I need to remove the `\0` from  `"%10g\0"`.

Before it was writing everything that's already in buffer into buffer, append `data[i]`-string and go to the next iteration. I want to write everything only once into the buffer, not `lengthData-1` times.

But how could I improve the readability? I need to keep track of how may bites I have left to write and where to write the next `data[i]` into the buffer.

2020-12-14 12:22 UTC, AnHeuermann commented on OMCompiler/SimulationRuntime/c/simulation/solver/sundials_error.c
> +      throwStreamPrint(NULL, "Buffer overflow!");
I think the way to go is using `strncat`.

2020-12-14 12:34 UTC, mahge commented on OMCompiler/SimulationRuntime/c/simulation/solver/sundials_error.c
> +      throwStreamPrint(NULL, "Buffer overflow!");
Yes I forgot to mention the `/0` on the last call to `snprintf`.  That is redundant. 

`strncat` might be good but you will still need to convert each double value to string using `snprintf` anyway. It might be a little bit clearer. 

Whichever way you go, add some comments to it. It is easier to understand once you know what the expected outcome is. Otherwise quite confusing. So mention what it is trying to do and how it does it, and it should be fine.

If you can you should move it to a utility function. So that it can be used in other places. The same pattern is used a few lines below. 

Even better is to look for a C++ utility file if we have one (we need one if not) and use C++ to do this things. It will be a lot easier and portable.

2020-12-14 12:52 UTC, mahge approved these changes

2020-12-14 12:55 UTC, AnHeuermann commented on OMCompiler/SimulationRuntime/c/simulation/solver/sundials_error.c
> +      throwStreamPrint(NULL, "Buffer overflow!");
I think this file get's coppied to FMUs, so it has to be ANSIC (more or less)

2020-12-14 12:56 UTC, AnHeuermann commented on OMCompiler/SimulationRuntime/c/simulation/solver/sundials_error.c
> +      throwStreamPrint(NULL, "Buffer overflow!");
But yes, a utility function is a good idea.

2020-12-14 13:03 UTC, mahge commented on OMCompiler/SimulationRuntime/c/simulation/solver/sundials_error.c
> +      throwStreamPrint(NULL, "Buffer overflow!");
`snprintf ` might not be ANSIC btw (I think it is C99). But since it can't be C++ it is probably the best option.

2020-12-14 13:28 UTC, sjoelund commented on OMCompiler/SimulationRuntime/c/simulation/solver/sundials_error.c
> +      throwStreamPrint(NULL, "Buffer overflow!");
FMI doesn't specify what C version is used. Even C18 might be allowed.

2020-12-14 13:47 UTC, AnHeuermann commented on OMCompiler/SimulationRuntime/c/simulation/solver/sundials_error.c
> +      throwStreamPrint(NULL, "Buffer overflow!");
Even better

2020-12-14 13:47 UTC, merged

2020-12-15 08:16 UTC, adrpo commented
This broke the compilation with MSVC it seems:
```
C:\dev\OM32bit\OMCompiler\SimulationRuntime\c\simulation\solver\sundials_error.c(796) : error C2057: expected constant expression
C:\dev\OM32bit\OMCompiler\SimulationRuntime\c\simulation\solver\sundials_error.c(796) : error C2466: cannot allocate an array of constant size 0
```

2020-12-15 08:16 UTC, adrpo commented
I will see if I can fix this.