Terminal process need a flag for new console
OpenModelica/OpenModelica pull request #7295
Opened 2021-03-12 10:16 UTC by adeas31

### Related Issues

Fixes #6413

### Purpose

Make it possible to open terminal window

### Approach

Pass CREATE_NEW_CONSOLE flag and remove STARTF_USESTDHANDLES flag for CreateProcess win32 api
Do not use QProcess::startDetached

2021-03-12 10:17 UTC, adeas31 commented
@AnHeuermann can you please check if this works on Linux as well?

2021-03-12 10:21 UTC, AnHeuermann commented
I only have WSL, so no real Linux. I don't think there is something OMEdit would be able to start, right?

2021-03-12 10:32 UTC, AnHeuermann commented
Okay, I've installed `konsole` which will open a new window with my usual byobu shell. But it doesn't seem to work from WSL, but again I don't know what to expect here.

2021-03-12 10:58 UTC, AnHeuermann commented
Now I tested on Windows as well and I don't think it is working as intended. When I click `Tools->Open Terminal` no change is visible. After I did something else, in my case open the options under `Tools->Options`, I got an output from CMD in the message browser, see below.

![image](https://user-images.githubusercontent.com/38031952/110930770-ceb81380-8329-11eb-87f5-c708d18d7072.png)

I would expect that a new CMD window will open. Did you try to start the terminal inside the message browser tab thing?

2021-03-12 10:59 UTC, AnHeuermann requested changes
It doesn't seem to work for me on Windows, see my previous comment.

2021-03-12 11:12 UTC, adeas31 commented
Are you sure you are using the changes from this PR? The error is what expected without this PR i.e., the terminal opened inside the OMEdit process.

2021-03-12 11:16 UTC, AnHeuermann reviewed
Okay I double checked because my Windows builds are fishy sometimes. An yes... I rebuild OMEdit again and now it works as expected.

2021-03-12 11:18 UTC, AnHeuermann approved these changes

2021-03-12 11:22 UTC, adeas31 commented
@sjoelund can you please test on Linux?

2021-03-12 11:25 UTC, lochel commented
Doesn't work for me on WSL2

2021-03-12 11:26 UTC, AnHeuermann commented
It seems that OMEdit doesn't uses the `DISPLAY` environment variable we are using for the X-server.

2021-03-12 12:10 UTC, sjoelund commented
It seems to work. But why do I need to set the terminal when it's part of the preferred applications in the OS?

2021-03-12 14:03 UTC, adeas31 commented
This is what we have  right now,

```
#ifdef Q_OS_WIN32
  mpTerminalCommandTextBox->setText("cmd.exe");
#elif defined(Q_OS_MAC)
  mpTerminalCommandTextBox->setText("");
#else
  mpTerminalCommandTextBox->setText("");
#endif
```

We can set some default for Linux as well.

2021-03-12 15:29 UTC, sjoelund commented
https://superuser.com/questions/1153988/find-the-default-terminal-emulator/1461079
I guess just put the Ubuntu default of `x-terminal-emulator`. Won't work for everyone, but if there is no good default way of doing it...

KDE has it in preferred applications, but we don't link to KDE things.

2021-03-15 08:37 UTC, hkiel commented
On macOS you could do with command=`open` and command-args=`/bin/bash`

2021-03-15 08:38 UTC, sjoelund commented
> On macOS you could do with command=`open` and command-args=`/bin/bash`

I thought zsh was the default shell now

2021-03-15 08:40 UTC, hkiel commented
I'm using Mojave and the default shell is bash there...

2021-03-15 08:43 UTC, hkiel commented
Looks like zsh-default comes with Catalina...
If we do not care, we could use `/bin/sh` instead!?

2021-03-15 09:04 UTC, adeas31 commented
I can't test macOS. @hkiel can you try what works for you and we can put that as a default. Alternatively, we can leave it empty as this will prompt user to set a terminal command and then they can set it to their preferred one.

2021-03-15 14:33 UTC, merged