First version newtonDiagnostics tool
OpenModelica/OpenModelica pull request #8489
Opened 2022-02-01 09:35 UTC by TeusvanderStelt

### Related Issues

### Purpose

### Approach

2022-02-01 09:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/OpenModelica/OpenModelica?pullRequest=8489) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/OpenModelica/OpenModelica?pullRequest=8489) before we can accept your contribution.<br/><hr/>**Teus van der Stelt** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/OpenModelica/OpenModelica?pullRequest=8489) it.</sub>

2022-02-01 10:09 UTC, mahge requested changes
The compilation is failing because both `newton_diagnostics.c` and `newton_diagnostics_with_debug.c` are being compiled by the CMake build system. 

I see that you have updated one of the CMakeLists files. However, we actually have two CMake compilation paths. I can understand it is a bit confusing. One of them is old and used just for MSVC compilation the other one is new/experimental and intended to be used in general.

Anyway without throwing too much information at you, the new CMake build collects source files by using a glob expression. So any source file in the folder simulation/solver will be compiled because of this
https://github.com/OpenModelica/OpenModelica/blob/1772c4b421f15d729b6d1b130e2bd105dc8252ac/OMCompiler/SimulationRuntime/c/cmake_3.14.cmake#L12-L15

You have added both source files (normal and debug) but only one of them is intended to be compiled. Why is the debug version file there? How and when should it be compiled instead of the normal one.

My suggestion is to remove the debug file and move its additional features to the `newton_diagnostics.c` protected by some debug signifying macro define. The two files are very similar and there is no point in carrying duplicate code. You can use one of the existing debug flags (@AnHeuermann any debug flags/macros that would make sense for this) or you can just add a custom macro define just for this.

2022-02-01 10:46 UTC, AnHeuermann commented
Theres already a debug flag added in [my initial commit](https://github.com/AnHeuermann/OpenModelica/commit/4e27b1105f667dbe75df6f58e177395fdb917990): `LOG_NLS_NEWTON_DIAG`.

That should be fine for debugging messages.

2022-02-14 13:27 UTC, AnHeuermann requested changes

2022-02-14 13:27 UTC, AnHeuermann commented on OMCompiler/SimulationRuntime/c/simulation/solver/newton_diagnostics.c
> +void MatMult( unsigned rA, unsigned cArB, unsigned cB, double A[rA][cArB], double B[cArB][cB], double C[rA][cB])
I guess this should be [DGEMM](http://www.netlib.org/lapack/explore-html/d1/d54/group__double__blas__level3_gaeda3cbd99c8fb834a60a6412878226e1.html)

2022-05-09 12:22 UTC, AnHeuermann commented
Hey @TeusvanderStelt. This PR seems to be stuck. Are you still working on this or should we close it for the time beeing?

2022-05-18 08:45 UTC, AnHeuermann commented
Closing this for now. @TeusvanderStelt can open a new PR when he's ready.

2022-05-18 08:45 UTC, closed without merging