Fixed control flags in the test files of GBODE
OpenModelica/OpenModelica pull request #9215
Opened 2022-07-08 06:59 UTC by bernhardbachmann

Original commit had still the old flag settings of -gbctrl for GBODE

2022-07-08 09:22 UTC, AnHeuermann requested changes
Mostly nitpicking that can be ignored.

Clarification on `rejectedType` would be great. I have no idea what that is.
`sprintf` should also be replaced by `snprintf` before crashing in a log, so we don't need to search for it later.

2022-07-08 09:22 UTC, AnHeuermann commented on OMCompiler/SimulationRuntime/c/simulation/solver/gbode_util.c
> +    //                     nIdx, idx);
Remove commented stuff?

```suggestion
```

2022-07-08 09:22 UTC, AnHeuermann commented on OMCompiler/SimulationRuntime/c/simulation/solver/gbode_main.c
> +        // gbData->stepSize = gbData->lastStepSize*IController(&(gbData->err_int), &(gbData->lastStepSize), 1);
Remove

```suggestion
```

2022-07-09 17:07 UTC, bernhardbachmann commented on OMCompiler/SimulationRuntime/c/simulation/solver/gbode_main.c
> +    warningStreamPrint(LOG_STDOUT, 0, "LOG_GBODE_STATES sets -noEquidistantTimeGrid for emitting results!");
Yes!
The activity diagram only works properly, if the equidistant time grid interpolation is disabled

2022-07-09 17:08 UTC, bernhardbachmann commented on OMCompiler/SimulationRuntime/c/simulation/solver/gbode_main.c
> +  gbfData->stepSize = 0.1*gbData->stepSize*IController(&(gbData->err_fast), &(gbData->stepSize), 1);
Only the IController can be used here. The other controller need more than one error value.

2022-07-09 17:10 UTC, bernhardbachmann commented on OMCompiler/SimulationRuntime/c/simulation/solver/gbode_util.c
> + * @param rejectedType Type of rejection
Explanation has been added to the source code

2022-07-09 17:11 UTC, bernhardbachmann commented on OMCompiler/SimulationRuntime/c/simulation/solver/gbode_util.c
> +    sprintf(fastStates_row, "%15.10g %2d %15.10g %15.10g %15.10g", time, rejectedType, gbData->err_slow, gbData->err_int, gbData->err_fast);
I tried snprintf, but it did not work for me. Need some help with this. Even your implementation of snprintf for the butcher tableau is inconsistent.

2022-07-09 17:20 UTC, bernhardbachmann commented on OMCompiler/SimulationRuntime/c/simulation/solver/gbode_main.c
> +        gbData->stepSize = gbData->lastStepSize * IController(gbData->errValues, gbData->stepSizeValues, gbData->tableau->error_order);
Done

2022-07-11 08:09 UTC, AnHeuermann commented on OMCompiler/SimulationRuntime/c/simulation/solver/gbode_util.c
> +    sprintf(fastStates_row, "%15.10g %2d %15.10g %15.10g %15.10g", time, rejectedType, gbData->err_slow, gbData->err_int, gbData->err_fast);
Fixed

2022-07-11 10:05 UTC, merged