add replaceSubModel() to GUI
OpenModelica/OpenModelica pull request #9469
Opened 2022-10-05 12:41 UTC by arun3688

### Purpose

This PR add support to `replaceSubModel()` API in `OMEDIT`

2022-10-05 13:21 UTC, adeas31 requested changes
This is wrong. See how `mpElementPropertiesAction` is implemented.

2022-10-11 19:12 UTC, arun3688 commented
@adeas31 removed the `replaceSubModelSignal` and performing the `ReplaceSubModelDialog`  in the slot with this https://github.com/OpenModelica/OpenModelica/pull/9469/commits/c06ad6aa7e30f9c4edf38f7b8149b5c88590afc9

2022-10-13 11:34 UTC, adeas31 requested changes
Its still using the signal from GraphicsView and you are connecting/disconnecting from it in itemChange.

2022-10-14 14:20 UTC, arun3688 commented
@adeas31 Now all the actions and slots are moved to Element class https://github.com/OpenModelica/OpenModelica/pull/9469/commits/4434112221cc8208d4ac3422210a87cc6fa5b129

2022-10-17 10:28 UTC, adeas31 requested changes
Looks better now. Please do the proposed changes and then hopefully we are good to go.

2022-10-17 10:28 UTC, adeas31 commented on OMEdit/OMEditLIB/Element/Element.cpp
> +
Remove this empty line.

2022-10-17 12:35 UTC, arun3688 commented on OMEdit/OMEditLIB/OMS/OMSProxy.cpp
> +  args << "\"" + cref + "\"" << fmuPath;
done

2022-10-17 12:35 UTC, arun3688 commented on OMEdit/OMEditLIB/Element/Element.cpp
> +  ReplaceSubModelDialog *pReplaceFMUDialog = new ReplaceSubModelDialog(mpGraphicsView, this->getName());
done with this https://github.com/OpenModelica/OpenModelica/pull/9469/commits/15e761d209907603f138ff663d36dd3600e7fb2b

2022-10-17 12:36 UTC, arun3688 commented on OMEdit/OMEditLIB/Element/Element.cpp
> +
done

2022-10-17 14:53 UTC, adeas31 approved these changes

2022-10-17 17:37 UTC, merged